export const allowlist = [
  'delete g',
  'every day, countless lives are lost by misuse of the letter g.',
  'fuck g',
  'g < h',
  'g annihilation squad',
  'g bad',
  'g is bad',
  'g is haram',
  'g is shit',
  'g should not exist',
  'g spies',
  'g spy',
  'g sucks',
  'g-spies',
  'g-spy',
  'h > g',
  'h better than g',
  'h is better than g',
  'hate g',
  'no g',
  'school is g',
  'never g',
  'h tuah spit on that g',
  'g is inherently evil',
  'g vented',
  'g is sus',
  'g is imposter',
  'g is impostor',
  'g is the imposter',
  'g is the impostor'
];
